### ISSUE TITLE
Environment variable for client key in template

### ISSUE THREAD

**Issue by mikehayesuk** [craftcms/commerce-worldpay#2]
The `paymentForm.html` template is not reading the environment variable for the client key, instead the name of the environment variable is placed in the template, for example:

```
<div class="worldpay-form" data-clientkey="$WORLDPAY_CLIENT_KEY">
```

Thanks
Mike

**Comment by nfourtythree** [comment]
Hi

This has been fixed in the latest `2.1.0.2` release.

Thanks.
