### ISSUE TITLE
Which Worldpay Gateways are supported with this plugin?

### ISSUE THREAD

**Issue by terryupton** [craftcms/commerce-worldpay#6]
### Description
WorldPay documentation along with their gateways, seem to be a bit of a rabbit hole.
Could you confirm which of the WorldPay Gateways are supported with this plugin?
https://developer.worldpay.com/docs 

From the above link, it looks like there are several types, but the main ones being:
1. Access Worldpay
2. Server Integration
3. WorldPay for Business (AKA Business Gateway 350) (Legacy?)
4. Worldwide Payment Gateway (Legacy?)

I have a client who currently has a WorldPay for Business and this seems incompatible with the current plugin, as the settings required are not consistent with that Gateway. So,. I am trying to guide them to speak with WorldPay to get them onto the right gateway/account to work with Craft Commerce.

The documentation and specifications are a little lacking, so I would greatly appreciate some clarity on this and any guidance you can offer. 

Commerce 3 and Craft 3.

**Comment by nfourtythree** [comment]
Hi @terryupton 

Thank you for your message.

We have updated the readme to reflect this as well but for clarity this plugin utilises the JSON restful API which is part of Worldpay's Online Payments API.

You can find documentation for the API here: https://developer.worldpay.com/docs/wpop

As mentioned the README has been updated so this should be more clear for people interested in this plugin.

Thanks!
